const express=require("express");
const router=express.Router();
const supabaseAdmin=require("../supabaseAdmin");
const{requireAuth}=require("../middleware/auth");
const{requireOrg}=require("../middleware/orgGuard");
router.use(requireAuth);router.use(requireOrg);
function canReview(req){return String(req.role||"").toLowerCase()==="superadmin"||!!req.orgMembership?.can_schedule_write||!!req.orgMembership?.is_admin;}
router.get("/",async(req,res)=>{try{if(!canReview(req))return res.status(403).json({error:"Edit Schedule permission is required"});const orgCode=req.orgCode||req.org_code;let q=supabaseAdmin.from("shift_requests").select("id,staff_id,department_id,shift_id,reason,created_at,start_date").eq("org_code",orgCode).eq("request_type","call_off").order("created_at",{ascending:false}).limit(100);if(req.orgMembership?.department_id&&String(req.role||"").toLowerCase()!=="superadmin")q=q.eq("department_id",req.orgMembership.department_id);const{data:rows,error}=await q;if(error)throw error;const staffIds=[...new Set((rows||[]).map(x=>x.staff_id).filter(Boolean))],shiftIds=[...new Set((rows||[]).map(x=>x.shift_id).filter(Boolean))];const[{data:staff,error:se},{data:shifts,error:he}]=await Promise.all([staffIds.length?supabaseAdmin.from("staff").select("id,name,role").in("id",staffIds):Promise.resolve({data:[]}),shiftIds.length?supabaseAdmin.from("shifts").select("id,staff_id,original_staff_id,role,shift_date,shift_type,start_local,end_local,open_reason,called_off_at").in("id",shiftIds).eq("org_code",orgCode):Promise.resolve({data:[]})]);if(se)throw se;if(he)throw he;const sm=Object.fromEntries((staff||[]).map(x=>[String(x.id),x])),hm=Object.fromEntries((shifts||[]).map(x=>[String(x.id),x]));res.json((rows||[]).map(r=>{const shift=hm[String(r.shift_id)]||null,replacement=shift?.staff_id&&String(shift.staff_id)!==String(r.staff_id);return{...r,employee:sm[String(r.staff_id)]||null,shift,coverage_status:replacement?"covered":shift?.staff_id==null?"uncovered":"changed"}}))}catch(e){console.error("CALL OFF COMMAND CENTER ERROR",e);res.status(500).json({error:e.message||"Unable to load call-offs"})}});
module.exports=router;
