const express=require("express");
const router=express.Router();
const supabaseAdmin=require("../supabaseAdmin");
const{requireAuth}=require("../middleware/auth");
const{requireOrg}=require("../middleware/orgGuard");
const{createNotifications,notifyEligibleForShift,notifyScheduleEditors}=require("../services/notificationService");
router.use(requireAuth);router.use(requireOrg);
const isNurse=v=>["RN","LPN","NURSE"].includes(String(v||"").trim().toUpperCase());
const compatible=(a,b)=>isNurse(a)?isNurse(b):String(a||"").toLowerCase()===String(b||"").toLowerCase();
async function me(req){const{data,error}=await supabaseAdmin.from("staff").select("id,name,role,user_id,department_id").eq("org_code",req.orgCode||req.org_code).eq("user_id",req.userId).maybeSingle();if(error)throw error;return data}
async function timeOff(org,staff,date){const{data,error}=await supabaseAdmin.from("shift_requests").select("id").eq("org_code",org).eq("staff_id",staff).eq("request_type","time_off").eq("status","approved").lte("start_date",date).gte("end_date",date).limit(1);if(error)throw error;return!!data?.length}
async function overlap(org,staff,shift){const{data,error}=await supabaseAdmin.from("shifts").select("id").eq("org_code",org).eq("staff_id",staff).neq("id",shift.id).lt("start_time",shift.end_time).gt("end_time",shift.start_time).limit(1);if(error)throw error;return!!data?.length}
router.post("/coverage",async(req,res)=>{try{const org=req.orgCode||req.org_code,staff=await me(req),{shift_id,note}=req.body||{};if(!staff)return res.status(400).json({error:"Your login is not linked to a staff record"});const{data:shift,error:se}=await supabaseAdmin.from("shifts").select("id,staff_id,role,shift_date,shift_type,start_local,end_local,start_time,end_time,department_id").eq("org_code",org).eq("id",shift_id).maybeSingle();if(se)throw se;if(!shift)return res.status(404).json({error:"Shift not found"});if(String(shift.staff_id)!==String(staff.id))return res.status(403).json({error:"That shift is not assigned to you"});const{data,error}=await supabaseAdmin.from("shift_requests").insert({org_code:org,user_id:req.userId,staff_id:staff.id,department_id:staff.department_id,request_type:"coverage",shift_id:shift.id,start_date:shift.shift_date,end_date:shift.shift_date,reason:note||null,status:"seeking_coverage"}).select().single();if(error?.code==="23505")return res.status(409).json({error:"You already requested coverage for this shift"});if(error)throw error;const notified=await notifyEligibleForShift({orgCode:org,shift,type:"coverage_available",title:"Coworker needs shift coverage",message:`${shift.shift_date} ${shift.shift_type} is available to cover for ${staff.name}.`,actionPath:"/coverage",excludeUserIds:[req.userId],metadata:{coverage_request_id:data.id,original_staff_id:staff.id}});res.json({...data,eligible_notified:notified.length})}catch(e){console.error("COVERAGE REQUEST ERROR",e);res.status(500).json({error:e?.message||"Unable to request coverage"})}});
router.get("/coverage/available",async(req,res)=>{try{const org=req.orgCode||req.org_code,staff=await me(req);if(!staff)return res.json([]);const{data,error}=await supabaseAdmin.from("shift_requests").select("id,staff_id,shift_id,reason,created_at").eq("org_code",org).eq("request_type","coverage").eq("status","seeking_coverage").neq("staff_id",staff.id).order("created_at");if(error)throw error;const out=[];for(const r of data||[]){const[{data:shift},{data:owner}]=await Promise.all([supabaseAdmin.from("shifts").select("id,staff_id,role,shift_date,shift_type,start_local,end_local,start_time,end_time,department_id").eq("id",r.shift_id).eq("org_code",org).maybeSingle(),supabaseAdmin.from("staff").select("name,role,department_id").eq("id",r.staff_id).eq("org_code",org).maybeSingle()]);if(!shift||String(shift.staff_id)!==String(r.staff_id)||String(shift.department_id||"")!==String(staff.department_id||"")||!compatible(shift.role,staff.role))continue;if(await timeOff(org,staff.id,shift.shift_date)||await overlap(org,staff.id,shift))continue;out.push({...r,shift,employee_name:owner?.name||"Coworker"})}res.json(out)}catch(e){console.error("AVAILABLE COVERAGE ERROR",e);res.status(500).json({error:"Unable to load coverage requests"})}});
router.post("/coverage/:id/volunteer",async(req,res)=>{try{const org=req.orgCode||req.org_code,staff=await me(req);if(!staff)return res.status(400).json({error:"Your login is not linked to a staff record"});const{data:r,error}=await supabaseAdmin.from("shift_requests").select("*").eq("id",req.params.id).eq("org_code",org).eq("request_type","coverage").eq("status","seeking_coverage").maybeSingle();if(error)throw error;if(!r)return res.status(404).json({error:"Coverage request is no longer available"});if(String(r.staff_id)===String(staff.id))return res.status(400).json({error:"You cannot cover your own shift"});const{data:shift}=await supabaseAdmin.from("shifts").select("*").eq("id",r.shift_id).eq("org_code",org).maybeSingle();if(!shift||String(shift.staff_id)!==String(r.staff_id))return res.status(409).json({error:"The shift assignment changed"});if(!compatible(shift.role,staff.role)||String(shift.department_id||"")!==String(staff.department_id||""))return res.status(400).json({error:"You are not eligible to cover this shift"});if(await timeOff(org,staff.id,shift.shift_date)||await overlap(org,staff.id,shift))return res.status(409).json({error:"This shift conflicts with your schedule or approved time off"});const now=new Date().toISOString();const{data:updated,error:ue}=await supabaseAdmin.from("shift_requests").update({status:"pending",target_staff_id:staff.id,target_user_id:req.userId,target_responded_at:now,target_accepted_at:now}).eq("id",r.id).eq("status","seeking_coverage").select().maybeSingle();if(ue)throw ue;if(!updated)return res.status(409).json({error:"Another employee already volunteered for this shift"});await Promise.all([createNotifications([{org_code:org,user_id:r.user_id,department_id:r.department_id,type:"coverage_found",title:"Coverage found",message:`${staff.name} volunteered to cover your shift. It is waiting for manager approval.`,action_path:"/requests",metadata:{request_id:r.id}}]),notifyScheduleEditors({orgId:req.orgId,orgCode:org,departmentId:r.department_id,type:"coverage_approval",title:"Shift coverage needs approval",message:`${staff.name} volunteered to cover a coworker's ${shift.shift_date} ${shift.shift_type} shift.`,actionPath:"/request-review",metadata:{request_id:r.id,shift_id:shift.id}})]);res.json(updated)}catch(e){console.error("COVERAGE VOLUNTEER ERROR",e);res.status(500).json({error:e?.message||"Unable to volunteer"})}});
module.exports=router;
