const express=require("express");
const router=express.Router();
const supabaseAdmin=require("../supabaseAdmin");
const {requireAuth}=require("../middleware/auth");
const {requireOrg}=require("../middleware/orgGuard");
router.use(requireAuth);router.use(requireOrg);
const validDate=v=>typeof v==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(v);
async function currentStaff(req){const{data}=await supabaseAdmin.from("staff").select("id,name,role,user_id").eq("org_code",req.orgCode||req.org_code).eq("user_id",req.userId).maybeSingle();return data||null}
router.get("/my",async(req,res)=>{try{const orgCode=req.orgCode||req.org_code;const{data,error}=await supabaseAdmin.from("shift_requests").select("id,request_type,shift_id,start_date,end_date,reason,status,created_at,decided_at,decision_note").eq("org_code",orgCode).eq("user_id",req.userId).order("created_at",{ascending:false}).limit(100);if(error)throw error;res.json(data||[])}catch(e){console.error("REQUEST MY ERROR",e);res.status(500).json({error:"Server error"})}});
router.post("/time-off",async(req,res)=>{try{const orgCode=req.orgCode||req.org_code;const{start_date,end_date,reason,shift_id}=req.body||{};const staff=await currentStaff(req);let start=start_date,end=end_date;if(shift_id){const{data:s}=await supabaseAdmin.from("shifts").select("id,shift_date,staff_id").eq("id",shift_id).eq("org_code",orgCode).maybeSingle();if(!s)return res.status(404).json({error:"Shift not found"});if(staff?.id&&String(s.staff_id)!==String(staff.id))return res.status(403).json({error:"That shift is not assigned to you"});start=s.shift_date;end=s.shift_date}if(!validDate(start)||!validDate(end)||end<start)return res.status(400).json({error:"Enter a valid start and end date"});const{data,error}=await supabaseAdmin.from("shift_requests").insert({org_code:orgCode,user_id:req.userId,staff_id:staff?.id||null,request_type:"time_off",shift_id:shift_id||null,start_date:start,end_date:end,reason:reason||null,status:"pending"}).select().single();if(error)throw error;res.json(data)}catch(e){console.error("TIME OFF REQUEST ERROR",e);res.status(500).json({error:"Unable to submit request"})}});
router.post("/pickup",async(req,res)=>{try{const orgCode=req.orgCode||req.org_code,{shift_id}=req.body||{};const staff=await currentStaff(req);const{data:shift}=await supabaseAdmin.from("shifts").select("id,staff_id,role,shift_date,shift_type").eq("id",shift_id).eq("org_code",orgCode).maybeSingle();if(!shift)return res.status(404).json({error:"Open shift not found"});if(shift.staff_id!==null)return res.status(409).json({error:"This shift is no longer open"});if(staff?.role&&shift.role&&String(staff.role).toLowerCase()!==String(shift.role).toLowerCase())return res.status(400).json({error:`This open shift is for ${shift.role}`});const{data,error}=await supabaseAdmin.from("shift_requests").insert({org_code:orgCode,user_id:req.userId,staff_id:staff?.id||null,request_type:"pickup",shift_id:shift.id,start_date:shift.shift_date,end_date:shift.shift_date,status:"pending"}).select().single();if(error?.code==="23505")return res.status(409).json({error:"You already requested this shift"});if(error)throw error;res.json(data)}catch(e){console.error("PICKUP REQUEST ERROR",e);res.status(500).json({error:"Unable to request shift"})}});
router.post("/offer",async(req,res)=>{try{const orgCode=req.orgCode||req.org_code,{shift_id,note}=req.body||{};const staff=await currentStaff(req);if(!staff)return res.status(400).json({error:"Your login is not linked to a staff record"});const{data:shift}=await supabaseAdmin.from("shifts").select("id,staff_id,shift_date").eq("id",shift_id).eq("org_code",orgCode).maybeSingle();if(!shift||String(shift.staff_id)!==String(staff.id))return res.status(403).json({error:"That shift is not assigned to you"});const{data,error}=await supabaseAdmin.from("shift_requests").insert({org_code:orgCode,user_id:req.userId,staff_id:staff.id,request_type:"offer",shift_id:shift.id,start_date:shift.shift_date,end_date:shift.shift_date,reason:note||null,status:"pending"}).select().single();if(error)throw error;res.json(data)}catch(e){console.error("OFFER REQUEST ERROR",e);res.status(500).json({error:"Unable to offer shift"})}});
router.get("/queue",async(req,res)=>{try{const m=req.orgMembership||{};if(String(req.role||"").toLowerCase()!=="superadmin"&&!m.can_schedule_write&&!m.is_admin)return res.status(403).json({error:"Schedule write permission required"});const orgCode=req.orgCode||req.org_code;const{data,error}=await supabaseAdmin.from("shift_requests").select("id,user_id,staff_id,request_type,shift_id,start_date,end_date,reason,status,created_at").eq("org_code",orgCode).eq("status","pending").order("created_at",{ascending:true});if(error)throw error;res.json(data||[])}catch(e){console.error("REQUEST QUEUE ERROR",e);res.status(500).json({error:"Server error"})}});
router.patch("/:id/decision",async(req,res)=>{try{const m=req.orgMembership||{};if(String(req.role||"").toLowerCase()!=="superadmin"&&!m.can_schedule_write&&!m.is_admin)return res.status(403).json({error:"Schedule write permission required"});const decision=String(req.body?.decision||"").toLowerCase();if(!["approved","denied"].includes(decision))return res.status(400).json({error:"Decision must be approved or denied"});const orgCode=req.orgCode||req.org_code;const{data:r}=await supabaseAdmin.from("shift_requests").select("*").eq("id",req.params.id).eq("org_code",orgCode).eq("status","pending").maybeSingle();if(!r)return res.status(404).json({error:"Pending request not found"});if(decision==="approved"&&r.request_type==="pickup"&&r.shift_id&&r.staff_id){const{data:s}=await supabaseAdmin.from("shifts").select("staff_id").eq("id",r.shift_id).eq("org_code",orgCode).maybeSingle();if(!s||s.staff_id!==null)return res.status(409).json({error:"Shift is no longer open"});await supabaseAdmin.from("shifts").update({staff_id:r.staff_id}).eq("id",r.shift_id).eq("org_code",orgCode)}const{data,error}=await supabaseAdmin.from("shift_requests").update({status:decision,decided_by:req.userId,decided_at:new Date().toISOString(),decision_note:req.body?.note||null}).eq("id",r.id).eq("org_code",orgCode).select().single();if(error)throw error;res.json(data)}catch(e){console.error("REQUEST DECISION ERROR",e);res.status(500).json({error:"Unable to update request"})}});
module.exports=router;
