const express=require("express");
const router=express.Router();
const supabaseAdmin=require("../supabaseAdmin");
const{requireAuth}=require("../middleware/auth");
const{requireOrg}=require("../middleware/orgGuard");
const{requireScheduleAccess}=require("../middleware/scheduleAccess");
const validDate=v=>typeof v==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(v);
const validTime=v=>typeof v==="string"&&/^(?:[01]\d|2[0-3]):[0-5]\d$/.test(v.slice(0,5));
function buildDateTime(date,time,timezone){const [y,m,d]=date.split("-").map(Number),[hh,mm]=time.slice(0,5).split(":").map(Number);const guess=new Date(Date.UTC(y,m-1,d,hh,mm));const parts=new Intl.DateTimeFormat("en-US",{timeZone:timezone,year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",hourCycle:"h23"}).formatToParts(guess);const get=t=>Number(parts.find(p=>p.type===t)?.value);const asUTC=Date.UTC(get("year"),get("month")-1,get("day"),get("hour"),get("minute"));return new Date(guess.getTime()+(guess.getTime()-asUTC)).toISOString()}
function computeTimes(date,start,end,timezone){const startUtc=buildDateTime(date,start,timezone);let endDate=date;if(end.slice(0,5)<=start.slice(0,5)){const d=new Date(`${date}T00:00:00Z`);d.setUTCDate(d.getUTCDate()+1);endDate=d.toISOString().slice(0,10)}return{startUtc,endUtc:buildDateTime(endDate,end,timezone)}}
async function timezone(orgId){const{data,error}=await supabaseAdmin.from("org_settings").select("timezone").eq("org_id",orgId).maybeSingle();if(error)throw error;let z=String(data?.timezone||"America/Los_Angeles");try{new Intl.DateTimeFormat("en-US",{timeZone:z}).format(new Date())}catch{z="America/Los_Angeles"}return z}
async function approvedTimeOff(orgCode,staffId,date){if(!staffId||!date)return null;const{data,error}=await supabaseAdmin.from("shift_requests").select("id,start_date,end_date,reason").eq("org_code",orgCode).eq("staff_id",staffId).eq("request_type","time_off").eq("status","approved").lte("start_date",date).gte("end_date",date).limit(1);if(error)throw error;return data?.[0]||null}
async function resolveTimes(orgCode,role,shiftType,startLocal,endLocal){if(String(shiftType).toLowerCase()==="custom"){const start=String(startLocal||"").slice(0,5),end=String(endLocal||"").slice(0,5);if(!validTime(start)||!validTime(end)||start===end)throw Object.assign(new Error("Custom shifts require valid, different start and end times"),{status:400});return{start,end}}const{data,error}=await supabaseAdmin.from("shift_settings").select("start_local,end_local").eq("org_code",orgCode).eq("role",role).eq("shift_type",shiftType).maybeSingle();if(error)throw error;if(!data)throw Object.assign(new Error(`No shift settings found for ${role} ${shiftType}`),{status:400});return{start:String(data.start_local).slice(0,5),end:String(data.end_local).slice(0,5)}}
router.use(requireAuth);router.use(requireOrg);router.use(requireScheduleAccess);
router.get("/",async(req,res)=>{try{const orgCode=req.orgCode||req.org_code,date=String(req.query.date||""),from=String(req.query.from||""),to=String(req.query.to||"");if((date&&!validDate(date))||(from&&!validDate(from))||(to&&!validDate(to)))return res.status(400).json({error:"Invalid date filter"});let q=supabaseAdmin.from("shifts").select("id,staff_id,role,shift_date,shift_type,start_local,end_local,start_time,end_time,timezone").eq("org_code",orgCode);if(date)q=q.eq("shift_date",date);else{if(from)q=q.gte("shift_date",from);if(to)q=q.lte("shift_date",to)}const{data,error}=await q.order("start_time");if(error)throw error;res.json(data||[])}catch(e){console.error("SHIFT GET ERROR",e);res.status(500).json({error:"Server error"})}});
router.post("/open",async(req,res)=>{try{const orgCode=req.orgCode||req.org_code,{role,shift_date,shiftType,start_local,end_local}=req.body||{};if(!role||!validDate(shift_date)||!shiftType)return res.status(400).json({error:"Role, date and shift are required"});const z=await timezone(req.orgId),t=await resolveTimes(orgCode,role,shiftType,start_local,end_local),u=computeTimes(shift_date,t.start,t.end,z);const{data,error}=await supabaseAdmin.from("shifts").insert({staff_id:null,role,unit:null,assignment_number:null,shift_date,shift_type:shiftType,start_local:t.start,end_local:t.end,start_time:u.startUtc,end_time:u.endUtc,timezone:z,org_code:orgCode}).select().single();if(error)throw error;res.json(data)}catch(e){console.error("OPEN SHIFT POST ERROR",e);res.status(e.status||500).json({error:e.message||"Server error"})}});
router.post("/",async(req,res)=>{try{const orgCode=req.orgCode||req.org_code,{staff_id,shift_date,shiftType,start_local,end_local}=req.body||{};if(!staff_id||!validDate(shift_date)||!shiftType)return res.status(400).json({error:"Staff, date and shift are required"});const leave=await approvedTimeOff(orgCode,staff_id,shift_date);if(leave)return res.status(409).json({error:"This employee has approved time off on this date.",code:"APPROVED_TIME_OFF",time_off:leave});const{data:staff}=await supabaseAdmin.from("staff").select("role").eq("id",staff_id).eq("org_code",orgCode).maybeSingle();if(!staff)return res.status(400).json({error:"Invalid staff_id"});const z=await timezone(req.orgId),t=await resolveTimes(orgCode,staff.role,shiftType,start_local,end_local),u=computeTimes(shift_date,t.start,t.end,z);const{data,error}=await supabaseAdmin.from("shifts").insert({staff_id,role:staff.role,unit:null,assignment_number:null,shift_date,shift_type:shiftType,start_local:t.start,end_local:t.end,start_time:u.startUtc,end_time:u.endUtc,timezone:z,org_code:orgCode}).select().single();if(error)throw error;res.json(data)}catch(e){console.error("SHIFT POST ERROR",e);res.status(e.status||500).json({error:e.message||"Server error"})}});
router.put("/:id",async(req,res)=>{try{const orgCode=req.orgCode||req.org_code,{staff_id,shift_date,shiftType,start_local,end_local}=req.body||{};if(!staff_id||!validDate(shift_date)||!shiftType)return res.status(400).json({error:"Staff, date and shift are required"});const leave=await approvedTimeOff(orgCode,staff_id,shift_date);if(leave)return res.status(409).json({error:"This employee has approved time off on this date.",code:"APPROVED_TIME_OFF",time_off:leave});const{data:staff}=await supabaseAdmin.from("staff").select("role").eq("id",staff_id).eq("org_code",orgCode).maybeSingle();if(!staff)return res.status(400).json({error:"Invalid staff_id"});const z=await timezone(req.orgId),t=await resolveTimes(orgCode,staff.role,shiftType,start_local,end_local),u=computeTimes(shift_date,t.start,t.end,z);const{data,error}=await supabaseAdmin.from("shifts").update({staff_id,role:staff.role,unit:null,assignment_number:null,shift_date,shift_type:shiftType,start_local:t.start,end_local:t.end,start_time:u.startUtc,end_time:u.endUtc,timezone:z}).eq("id",req.params.id).eq("org_code",orgCode).select().maybeSingle();if(error)throw error;if(!data)return res.status(404).json({error:"Shift not found in this organization"});res.json(data)}catch(e){console.error("SHIFT PUT ERROR",e);res.status(e.status||500).json({error:e.message||"Server error"})}});
router.delete("/:id",async(req,res)=>{try{const{data,error}=await supabaseAdmin.from("shifts").delete().eq("id",req.params.id).eq("org_code",req.orgCode||req.org_code).select("id");if(error)throw error;if(!data?.length)return res.status(404).json({error:"Shift not found in this organization"});res.json({message:"Shift deleted"})}catch(e){console.error("SHIFT DELETE ERROR",e);res.status(500).json({error:"Server error"})}});
module.exports=router;
