const express=require("express");
const router=express.Router();
const supabaseAdmin=require("../supabaseAdmin");
const {requireAuth}=require("../middleware/auth");
const {requireOrg}=require("../middleware/orgGuard");
router.use(requireAuth);router.use(requireOrg);
const validDate=v=>typeof v==="string"&&/^\d{4}-\d{2}-\d{2}$/.test(v);
const isNurseRole=v=>["RN","LPN","NURSE"].includes(String(v||"").trim().toUpperCase());
async function currentStaff(req){const{data}=await supabaseAdmin.from("staff").select("id,name,role,user_id,department_id").eq("org_code",req.orgCode||req.org_code).eq("user_id",req.userId).maybeSingle();return data||null}
async function hasApprovedTimeOff(orgCode,staffId,date){if(!staffId||!date)return false;const{data,error}=await supabaseAdmin.from("shift_requests").select("id").eq("org_code",orgCode).eq("staff_id",staffId).eq("request_type","time_off").eq("status","approved").lte("start_date",date).gte("end_date",date).limit(1);if(error)throw error;return!!data?.length}
async function hasScheduleEditor(req,departmentId){if(!departmentId||!req.orgId)return false;const{count,error}=await supabaseAdmin.from("org_memberships").select("user_id",{count:"exact",head:true}).eq("org_id",req.orgId).eq("department_id",departmentId).eq("is_active",true).eq("can_schedule_write",true);if(error)throw error;return(count||0)>0}
function platformReviewer(req){return String(req.role||"").toLowerCase()==="superadmin"}
function canSeeSchedule(req){const m=req.orgMembership||{};return platformReviewer(req)||!!m.can_schedule_read||!!m.can_schedule_write||!!m.is_admin}
function reviewDepartment(req){const m=req.orgMembership||{};if(!m.can_schedule_write||!m.department_id)return null;return String(m.department_id)}
async function mayReviewRequest(req,r){if(platformReviewer(req))return true;const dept=reviewDepartment(req);return !!dept&&String(r?.department_id||"")===dept}
router.get("/review-access",async(req,res)=>{try{const dept=reviewDepartment(req),can_review=platformReviewer(req)||!!dept;let pending_count=0;if(can_review){let q=supabaseAdmin.from("shift_requests").select("id",{count:"exact",head:true}).eq("org_code",req.orgCode||req.org_code).eq("status","pending");if(!platformReviewer(req))q=q.eq("department_id",dept);const{count,error}=await q;if(error)throw error;pending_count=count||0}res.json({can_review,pending_count})}catch(e){console.error("REVIEW ACCESS ERROR",e);res.status(500).json({error:"Server error"})}});
router.get("/open-shifts",async(req,res)=>{try{const orgCode=req.orgCode||req.org_code;const from=String(req.query.from||new Date().toISOString().slice(0,10)),to=String(req.query.to||"");if(!validDate(from)||(to&&!validDate(to)))return res.status(400).json({error:"Invalid date range"});const staff=await currentStaff(req);let q=supabaseAdmin.from("shifts").select("id,role,shift_date,shift_type,start_local,end_local,start_time,end_time").eq("org_code",orgCode).is("staff_id",null).gte("shift_date",from);if(to)q=q.lte("shift_date",to);if(staff?.role){if(isNurseRole(staff.role))q=q.in("role",["Nurse","RN","LPN"]);else q=q.eq("role",staff.role)}const{data,error}=await q.order("shift_date",{ascending:true}).order("start_time",{ascending:true});if(error)throw error;res.json((data||[]).map(x=>({...x,role:isNurseRole(x.role)?"Nurse":x.role})))}catch(e){console.error("OPEN SHIFTS ERROR",e);res.status(500).json({error:"Server error"})}});
router.get("/approved-time-off",async(req,res)=>{try{if(!canSeeSchedule(req))return res.status(403).json({error:"Schedule access required"});const orgCode=req.orgCode||req.org_code,from=String(req.query.from||""),to=String(req.query.to||"");if(!validDate(from)||!validDate(to)||from>to)return res.status(400).json({error:"Valid from/to dates are required"});const{data,error}=await supabaseAdmin.from("shift_requests").select("id,staff_id,start_date,end_date,reason,decided_at").eq("org_code",orgCode).eq("request_type","time_off").eq("status","approved").lte("start_date",to).gte("end_date",from).order("start_date");if(error)throw error;res.json(data||[])}catch(e){console.error("APPROVED TIME OFF ERROR",e);res.status(500).json({error:"Server error"})}});
router.get("/my",async(req,res)=>{try{const orgCode=req.orgCode||req.org_code;const{data,error}=await supabaseAdmin.from("shift_requests").select("id,request_type,shift_id,start_date,end_date,reason,status,created_at,decided_at,decision_note,department_id,employee_seen_at").eq("org_code",orgCode).eq("user_id",req.userId).order("created_at",{ascending:false}).limit(100);if(error)throw error;res.json(data||[])}catch(e){console.error("REQUEST MY ERROR",e);res.status(500).json({error:"Server error"})}});
router.patch("/:id/seen",async(req,res)=>{try{const orgCode=req.orgCode||req.org_code;const{data,error}=await supabaseAdmin.from("shift_requests").update({employee_seen_at:new Date().toISOString()}).eq("id",req.params.id).eq("org_code",orgCode).eq("user_id",req.userId).neq("status","pending").select("id,employee_seen_at").maybeSingle();if(error)throw error;if(!data)return res.status(404).json({error:"Notification not found"});res.json(data)}catch(e){console.error("REQUEST SEEN ERROR",e);res.status(500).json({error:"Unable to mark notification read"})}});
router.post("/time-off",async(req,res)=>{try{const orgCode=req.orgCode||req.org_code;const{start_date,end_date,reason,shift_id}=req.body||{};const staff=await currentStaff(req);if(!staff)return res.status(400).json({error:"Your login is not linked to a staff record"});if(!staff.department_id)return res.status(400).json({error:"Your staff profile is not assigned to a department"});if(!(await hasScheduleEditor(req,staff.department_id)))return res.status(409).json({error:"Your department does not have anyone with Edit Schedule permission to review requests yet"});let start=start_date,end=end_date;if(shift_id){const{data:s}=await supabaseAdmin.from("shifts").select("id,shift_date,staff_id").eq("id",shift_id).eq("org_code",orgCode).maybeSingle();if(!s)return res.status(404).json({error:"Shift not found"});if(String(s.staff_id)!==String(staff.id))return res.status(403).json({error:"That shift is not assigned to you"});start=s.shift_date;end=s.shift_date}if(!validDate(start)||!validDate(end)||end<start)return res.status(400).json({error:"Enter a valid start and end date"});const{data,error}=await supabaseAdmin.from("shift_requests").insert({org_code:orgCode,user_id:req.userId,staff_id:staff.id,department_id:staff.department_id,request_type:"time_off",shift_id:shift_id||null,start_date:start,end_date:end,reason:reason||null,status:"pending"}).select().single();if(error)throw error;res.json(data)}catch(e){console.error("TIME OFF REQUEST ERROR",e);res.status(500).json({error:e?.message||"Unable to submit request"})}});
router.post("/pickup",async(req,res)=>{try{const orgCode=req.orgCode||req.org_code,{shift_id}=req.body||{};const staff=await currentStaff(req);if(!staff)return res.status(400).json({error:"Your login is not linked to a staff record"});if(!staff.department_id)return res.status(400).json({error:"Your staff profile is not assigned to a department"});if(!(await hasScheduleEditor(req,staff.department_id)))return res.status(409).json({error:"Your department does not have anyone with Edit Schedule permission to review requests yet"});const{data:shift}=await supabaseAdmin.from("shifts").select("id,staff_id,role,shift_date,shift_type").eq("id",shift_id).eq("org_code",orgCode).maybeSingle();if(!shift)return res.status(404).json({error:"Open shift not found"});if(shift.staff_id!==null)return res.status(409).json({error:"This shift is no longer open"});const compatible=isNurseRole(shift.role)?isNurseRole(staff.role):String(staff.role||"").toLowerCase()===String(shift.role||"").toLowerCase();if(!compatible)return res.status(400).json({error:`This open shift is for ${isNurseRole(shift.role)?"Nurse":shift.role}`});if(await hasApprovedTimeOff(orgCode,staff.id,shift.shift_date))return res.status(409).json({error:"You have approved time off on this date"});const{data,error}=await supabaseAdmin.from("shift_requests").insert({org_code:orgCode,user_id:req.userId,staff_id:staff.id,department_id:staff.department_id,request_type:"pickup",shift_id:shift.id,start_date:shift.shift_date,end_date:shift.shift_date,status:"pending"}).select().single();if(error?.code==="23505")return res.status(409).json({error:"You already requested this shift"});if(error)throw error;res.json(data)}catch(e){console.error("PICKUP REQUEST ERROR",e);res.status(500).json({error:e?.message||"Unable to request shift"})}});
router.post("/offer",async(req,res)=>{try{const orgCode=req.orgCode||req.org_code,{shift_id,note}=req.body||{};const staff=await currentStaff(req);if(!staff)return res.status(400).json({error:"Your login is not linked to a staff record"});if(!staff.department_id)return res.status(400).json({error:"Your staff profile is not assigned to a department"});if(!(await hasScheduleEditor(req,staff.department_id)))return res.status(409).json({error:"Your department does not have anyone with Edit Schedule permission to review requests yet"});const{data:shift}=await supabaseAdmin.from("shifts").select("id,staff_id,shift_date").eq("id",shift_id).eq("org_code",orgCode).maybeSingle();if(!shift||String(shift.staff_id)!==String(staff.id))return res.status(403).json({error:"That shift is not assigned to you"});const{data,error}=await supabaseAdmin.from("shift_requests").insert({org_code:orgCode,user_id:req.userId,staff_id:staff.id,department_id:staff.department_id,request_type:"offer",shift_id:shift.id,start_date:shift.shift_date,end_date:shift.shift_date,reason:note||null,status:"pending"}).select().single();if(error)throw error;res.json(data)}catch(e){console.error("OFFER REQUEST ERROR",e);res.status(500).json({error:e?.message||"Unable to offer shift"})}});
router.get("/queue",async(req,res)=>{try{const orgCode=req.orgCode||req.org_code,dept=reviewDepartment(req);if(!platformReviewer(req)&&!dept)return res.status(403).json({error:"Edit Schedule permission is required to review department requests"});let q=supabaseAdmin.from("shift_requests").select("id,user_id,staff_id,department_id,request_type,shift_id,start_date,end_date,reason,status,created_at").eq("org_code",orgCode).eq("status","pending").order("created_at",{ascending:true});if(!platformReviewer(req))q=q.eq("department_id",dept);const{data,error}=await q;if(error)throw error;const rows=await Promise.all((data||[]).map(async r=>{let conflict_count=0,shift=null;if(r.request_type==="time_off"&&r.staff_id&&r.start_date&&r.end_date){const{count}=await supabaseAdmin.from("shifts").select("id",{count:"exact",head:true}).eq("org_code",orgCode).eq("staff_id",r.staff_id).gte("shift_date",r.start_date).lte("shift_date",r.end_date);conflict_count=count||0}if(r.shift_id){const{data:s}=await supabaseAdmin.from("shifts").select("id,role,shift_date,shift_type,start_local,end_local,staff_id").eq("org_code",orgCode).eq("id",r.shift_id).maybeSingle();shift=s?{...s,role:isNurseRole(s.role)?"Nurse":s.role}:null}return{...r,conflict_count,shift}}));res.json(rows)}catch(e){console.error("REQUEST QUEUE ERROR",e);res.status(500).json({error:"Server error"})}});
router.patch("/:id/decision",async(req,res)=>{try{const decision=String(req.body?.decision||"").toLowerCase();if(!["approved","denied"].includes(decision))return res.status(400).json({error:"Decision must be approved or denied"});const orgCode=req.orgCode||req.org_code;const{data:r}=await supabaseAdmin.from("shift_requests").select("*").eq("id",req.params.id).eq("org_code",orgCode).eq("status","pending").maybeSingle();if(!r)return res.status(404).json({error:"Pending request not found"});if(!(await mayReviewRequest(req,r)))return res.status(403).json({error:"Edit Schedule permission is required for this employee's department"});let opened_shifts=0;if(decision==="approved"&&r.request_type==="pickup"&&r.shift_id&&r.staff_id){const[{data:s},{data:pickupStaff}]=await Promise.all([supabaseAdmin.from("shifts").select("staff_id,shift_date").eq("id",r.shift_id).eq("org_code",orgCode).maybeSingle(),supabaseAdmin.from("staff").select("role").eq("id",r.staff_id).eq("org_code",orgCode).maybeSingle()]);if(!s||s.staff_id!==null)return res.status(409).json({error:"Shift is no longer open"});if(!pickupStaff)return res.status(409).json({error:"Employee is no longer active in this facility"});if(await hasApprovedTimeOff(orgCode,r.staff_id,s.shift_date))return res.status(409).json({error:"Employee has approved time off on this date"});const{error:pickupErr}=await supabaseAdmin.from("shifts").update({staff_id:r.staff_id,role:pickupStaff.role}).eq("id",r.shift_id).eq("org_code",orgCode);if(pickupErr)throw pickupErr}
if(decision==="approved"&&r.request_type==="time_off"&&r.staff_id){const{data:conflicts,error:ce}=await supabaseAdmin.from("shifts").select("id").eq("org_code",orgCode).eq("staff_id",r.staff_id).gte("shift_date",r.start_date).lte("shift_date",r.end_date);if(ce)throw ce;if(conflicts?.length){const ids=conflicts.map(x=>x.id);const{error:ue}=await supabaseAdmin.from("shifts").update({staff_id:null}).in("id",ids).eq("org_code",orgCode);if(ue)throw ue;opened_shifts=ids.length}}
const{data,error}=await supabaseAdmin.from("shift_requests").update({status:decision,decided_by:req.userId,decided_at:new Date().toISOString(),decision_note:req.body?.note||null,employee_seen_at:null}).eq("id",r.id).eq("org_code",orgCode).eq("status","pending").select().single();if(error)throw error;res.json({...data,opened_shifts})}catch(e){console.error("REQUEST DECISION ERROR",e);res.status(500).json({error:e?.message||"Unable to update request"})}});
module.exports=router;
