const express=require("express");
const router=express.Router();
const supabaseAdmin=require("../supabaseAdmin");
const{requireAuth}=require("../middleware/auth");
const{requireOrg}=require("../middleware/orgGuard");
const{createNotifications,notifyScheduleEditors}=require("../services/notificationService");
router.use(requireAuth);router.use(requireOrg);
const isNurse=v=>["RN","LPN","NURSE"].includes(String(v||"").trim().toUpperCase());
const compatible=(a,b)=>isNurse(a)?isNurse(b):String(a||"").toLowerCase()===String(b||"").toLowerCase();
async function me(req){const{data,error}=await supabaseAdmin.from("staff").select("id,name,role,user_id,department_id").eq("org_code",req.orgCode||req.org_code).eq("user_id",req.userId).maybeSingle();if(error)throw error;return data}
async function timeOff(org,staff,date){const{data,error}=await supabaseAdmin.from("shift_requests").select("id").eq("org_code",org).eq("staff_id",staff).eq("request_type","time_off").eq("status","approved").lte("start_date",date).gte("end_date",date).limit(1);if(error)throw error;return!!data?.length}
async function overlap(org,staff,shift,exclude=[]){const{data,error}=await supabaseAdmin.from("shifts").select("id,start_time,end_time").eq("org_code",org).eq("staff_id",staff).lt("start_time",shift.end_time).gt("end_time",shift.start_time);if(error)throw error;return(data||[]).some(x=>!exclude.map(String).includes(String(x.id)))}

router.get("/trade-options/:shiftId",async(req,res)=>{try{const org=req.orgCode||req.org_code,staff=await me(req);if(!staff)return res.status(400).json({error:"Your login is not linked to a staff record"});const{data:mine,error:se}=await supabaseAdmin.from("shifts").select("id,staff_id,role,shift_date,start_time,end_time,start_local,end_local,department_id,shift_type").eq("org_code",org).eq("id",req.params.shiftId).maybeSingle();if(se)throw se;if(!mine||String(mine.staff_id)!==String(staff.id))return res.status(403).json({error:"That shift is not assigned to you"});const{data:rows,error}=await supabaseAdmin.from("shifts").select("id,staff_id,role,shift_date,start_time,end_time,start_local,end_local,department_id,shift_type").eq("org_code",org).neq("staff_id",staff.id).not("staff_id","is",null).gte("shift_date",new Date().toISOString().slice(0,10)).order("shift_date").limit(120);if(error)throw error;const ids=[...new Set((rows||[]).map(x=>x.staff_id))];const{data:people,error:pe}=ids.length?await supabaseAdmin.from("staff").select("id,name,role,user_id,department_id").eq("org_code",org).in("id",ids):{data:[],error:null};if(pe)throw pe;const byId=new Map((people||[]).map(x=>[String(x.id),x]));const options=[];for(const x of rows||[]){const p=byId.get(String(x.staff_id));if(!p?.user_id||String(p.department_id||"")!==String(staff.department_id||"")||!compatible(staff.role,p.role)||!compatible(mine.role,x.role))continue;if(await timeOff(org,staff.id,x.shift_date)||await timeOff(org,p.id,mine.shift_date))continue;if(await overlap(org,staff.id,x,[mine.id,x.id])||await overlap(org,p.id,mine,[mine.id,x.id]))continue;options.push({...x,employee_name:p.name,target_staff_id:p.id,target_user_id:p.user_id,role:isNurse(x.role)?"Nurse":x.role})}res.json(options)}catch(e){console.error("TRADE OPTIONS ERROR",e);res.status(500).json({error:e?.message||"Unable to load trade options"})}});

router.post("/trade",async(req,res)=>{try{const org=req.orgCode||req.org_code,staff=await me(req),{shift_id,target_shift_id,note}=req.body||{};if(!staff)return res.status(400).json({error:"Your login is not linked to a staff record"});const{data:mine}=await supabaseAdmin.from("shifts").select("*").eq("org_code",org).eq("id",shift_id).maybeSingle(),{data:theirs}=await supabaseAdmin.from("shifts").select("*").eq("org_code",org).eq("id",target_shift_id).maybeSingle();if(!mine||String(mine.staff_id)!==String(staff.id))return res.status(403).json({error:"Your shift assignment changed"});if(!theirs?.staff_id)return res.status(409).json({error:"The requested trade shift is no longer assigned"});const{data:target}=await supabaseAdmin.from("staff").select("id,name,role,user_id,department_id").eq("org_code",org).eq("id",theirs.staff_id).maybeSingle();if(!target?.user_id||String(target.department_id||"")!==String(staff.department_id||"")||!compatible(staff.role,target.role))return res.status(400).json({error:"That employee is not eligible for this trade"});if(await timeOff(org,staff.id,theirs.shift_date)||await timeOff(org,target.id,mine.shift_date))return res.status(409).json({error:"This trade conflicts with approved time off"});if(await overlap(org,staff.id,theirs,[mine.id,theirs.id])||await overlap(org,target.id,mine,[mine.id,theirs.id]))return res.status(409).json({error:"This trade would create an overlapping shift"});const{data,error}=await supabaseAdmin.from("shift_requests").insert({org_code:org,user_id:req.userId,staff_id:staff.id,department_id:staff.department_id,request_type:"trade",shift_id:mine.id,target_shift_id:theirs.id,target_staff_id:target.id,target_user_id:target.user_id,start_date:mine.shift_date,end_date:theirs.shift_date,reason:note||null,status:"awaiting_employee"}).select().single();if(error?.code==="23505")return res.status(409).json({error:"You already have an active trade request for this shift"});if(error)throw error;await createNotifications([{org_code:org,user_id:target.user_id,department_id:target.department_id,type:"trade_request",title:"Shift trade request",message:`${staff.name} wants to trade shifts with you.`,action_path:"/my-schedule",metadata:{request_id:data.id,shift_id:mine.id,target_shift_id:theirs.id}}]);res.json(data)}catch(e){console.error("TRADE REQUEST ERROR",e);res.status(500).json({error:e?.message||"Unable to request trade"})}});

router.get("/trades/incoming",async(req,res)=>{try{const org=req.orgCode||req.org_code;const{data,error}=await supabaseAdmin.from("shift_requests").select("id,user_id,staff_id,shift_id,target_shift_id,target_staff_id,start_date,end_date,reason,status,created_at").eq("org_code",org).eq("request_type","trade").eq("target_user_id",req.userId).eq("status","awaiting_employee").order("created_at",{ascending:false});if(error)throw error;const out=await Promise.all((data||[]).map(async r=>{const[{data:from},{data:a},{data:b}]=await Promise.all([supabaseAdmin.from("staff").select("name").eq("id",r.staff_id).maybeSingle(),supabaseAdmin.from("shifts").select("id,shift_date,start_local,end_local,role").eq("id",r.shift_id).maybeSingle(),supabaseAdmin.from("shifts").select("id,shift_date,start_local,end_local,role").eq("id",r.target_shift_id).maybeSingle()]);return{...r,requester_name:from?.name||"Coworker",requester_shift:a,your_shift:b}}));res.json(out)}catch(e){console.error("INCOMING TRADES ERROR",e);res.status(500).json({error:"Unable to load trade requests"})}});

router.patch("/trades/:id/respond",async(req,res)=>{try{const org=req.orgCode||req.org_code,accept=!!req.body?.accept;const{data:r,error}=await supabaseAdmin.from("shift_requests").select("*").eq("id",req.params.id).eq("org_code",org).eq("request_type","trade").eq("target_user_id",req.userId).eq("status","awaiting_employee").maybeSingle();if(error)throw error;if(!r)return res.status(404).json({error:"Trade request is no longer available"});const status=accept?"pending":"declined";const now=new Date().toISOString();const{data:updated,error:ue}=await supabaseAdmin.from("shift_requests").update({status,target_responded_at:now,target_accepted_at:accept?now:null}).eq("id",r.id).select().single();if(ue)throw ue;await createNotifications([{org_code:org,user_id:r.user_id,department_id:r.department_id,type:"trade_response",title:accept?"Trade accepted":"Trade declined",message:accept?"Your coworker accepted the trade. It is now waiting for manager approval.":"Your coworker declined the trade request.",action_path:"/requests",metadata:{request_id:r.id}}]);if(accept)await notifyScheduleEditors({orgId:req.orgId,orgCode:org,departmentId:r.department_id,type:"trade_approval",title:"Shift trade needs approval",message:"Both employees agreed to a shift trade. Review it before the schedule changes.",actionPath:"/request-review",metadata:{request_id:r.id}});res.json(updated)}catch(e){console.error("TRADE RESPONSE ERROR",e);res.status(500).json({error:e?.message||"Unable to respond to trade"})}});
module.exports=router;
