import {useEffect,useMemo,useState} from "react";
import api from "../services/api";
const fmtDate=v=>v?new Date(`${String(v).slice(0,10)}T00:00:00`).toLocaleDateString(undefined,{weekday:"short",month:"short",day:"numeric"}):"";
const fmtTime=v=>{if(!v)return"";const m=String(v).match(/^(\d{1,2}):(\d{2})/);if(!m)return String(v);let h=Number(m[1]),ap=h>=12?"PM":"AM";h=h%12||12;return`${h}:${m[2]} ${ap}`};
const shiftLine=s=>[fmtDate(s?.shift_date||s?.date),s?.start_local&&s?.end_local?`${fmtTime(s.start_local)}–${fmtTime(s.end_local)}`:"",s?.role||s?.shift_type].filter(Boolean).join(" • ");
export default function CoverageCenterPage(){const[tab,setTab]=useState("mine"),[mine,setMine]=useState([]),[available,setAvailable]=useState([]),[loading,setLoading]=useState(true),[busy,setBusy]=useState(null),[notice,setNotice]=useState("");
async function load(){setLoading(true);setNotice("");try{const month=new Date().toISOString().slice(0,7);const[summary,coverage]=await Promise.all([api.get(`/me/home-summary?month=${month}`),api.get("/shift-requests/coverage/available")]);const today=new Date().toISOString().slice(0,10);setMine((summary?.myShifts||[]).filter(x=>String(x.shift_date||x.date||"").slice(0,10)>=today));setAvailable(Array.isArray(coverage)?coverage:[])}catch(e){setNotice(e?.message||"Unable to load coverage center") }finally{setLoading(false)}}
useEffect(()=>{load()},[]);const rows=useMemo(()=>tab==="mine"?mine:available,[tab,mine,available]);
async function requestCoverage(shift){const note=prompt("Note for coworkers (optional):")||"";setBusy(`mine-${shift.id}`);try{const r=await api.post("/shift-requests/coverage",{shift_id:shift.id,note:note||null});setNotice(`Coverage request posted. ${r?.eligible_notified||0} eligible coworker${r?.eligible_notified===1?"":"s"} notified.`);await load()}catch(e){setNotice(e?.message||"Unable to request coverage")}finally{setBusy(null)}}
async function volunteer(r){if(!confirm(`Volunteer to cover ${r.employee_name}'s ${fmtDate(r.shift?.shift_date)} shift? Management must approve the change.`))return;setBusy(`cover-${r.id}`);try{await api.post(`/shift-requests/coverage/${r.id}/volunteer`,{});setNotice("You volunteered. The coverage change is now waiting for manager approval.");await load()}catch(e){setNotice(e?.message||"Unable to volunteer")}finally{setBusy(null)}}
return <main style={s.page}><div style={s.head}><div><h1 style={s.h1}>Coverage Center</h1><div style={s.sub}>Get a shift covered before calling off, or help cover a coworker.</div></div><button style={s.btn} onClick={load}>↻</button></div><div style={s.steps}><div><b>1. Ask for coverage</b><span>Your shift stays assigned to you.</span></div><div><b>2. Coworker volunteers</b><span>ShiftCensus checks eligibility and conflicts.</span></div><div><b>3. Manager approves</b><span>Only then does the official schedule change.</span></div></div>{notice&&<div style={s.notice}>{notice}</div>}<div style={s.tabs}><button style={tab==="mine"?s.active:s.tab} onClick={()=>setTab("mine")}>Get My Shift Covered</button><button style={tab==="available"?s.active:s.tab} onClick={()=>setTab("available")}>Available to Cover ({available.length})</button></div><section style={s.card}>{loading?<div style={s.empty}>Loading…</div>:rows.length===0?<div style={s.empty}>{tab==="mine"?"No upcoming shifts available for coverage requests.":"No coworker coverage requests match your role and availability."}</div>:rows.map(row=>{const shift=tab==="mine"?row:row.shift;return <div key={tab==="mine"?row.id:row.id} style={s.row}><div><b>{shiftLine(shift)||"Shift"}</b>{tab==="available"&&<div style={s.meta}>Covering for {row.employee_name}{row.reason?` • ${row.reason}`:""}</div>}<div style={s.meta}>{tab==="mine"?"Your shift remains yours until someone volunteers and management approves.":"Volunteering does not change the schedule until management approves."}</div></div>{tab==="mine"?<button style={s.primary} disabled={!!busy} onClick={()=>requestCoverage(shift)}>{busy===`mine-${shift.id}`?"Posting…":"Find Coverage"}</button>:<button style={s.primary} disabled={!!busy} onClick={()=>volunteer(row)}>{busy===`cover-${row.id}`?"Submitting…":"I Can Cover"}</button>}</div>})}</section><div style={s.callout}><b>Still unable to work?</b><span>If coverage is not found and you need to call off, use <b>My Schedule → Call Off Shift</b>. A call-off is recorded separately from whether the shift gets covered.</span></div></main>}
const s={page:{width:"min(820px,100%)",margin:"0 auto",padding:"22px 14px 50px",boxSizing:"border-box",color:"var(--text)"},head:{display:"flex",justifyContent:"space-between",gap:12,alignItems:"center",marginBottom:16},h1:{margin:0,fontSize:30},sub:{opacity:.65,marginTop:4},btn:{padding:"9px 12px",borderRadius:10,border:"1px solid var(--border)",background:"var(--surface)",color:"inherit",fontWeight:800},steps:{display:"grid",gridTemplateColumns:"repeat(auto-fit,minmax(180px,1fr))",gap:8,marginBottom:14},notice:{padding:12,borderRadius:12,border:"1px solid #2563eb",background:"rgba(37,99,235,.1)",marginBottom:12},tabs:{display:"grid",gridTemplateColumns:"1fr 1fr",gap:8,marginBottom:12},tab:{padding:12,borderRadius:12,border:"1px solid var(--border)",background:"var(--surface)",color:"inherit",fontWeight:800},active:{padding:12,borderRadius:12,border:"1px solid #3b82f6",background:"rgba(37,99,235,.12)",color:"inherit",fontWeight:900},card:{border:"1px solid var(--border)",background:"var(--surface)",borderRadius:16,padding:14},row:{display:"flex",justifyContent:"space-between",alignItems:"center",gap:14,padding:"14px 4px",borderBottom:"1px solid var(--border)"},meta:{fontSize:12,opacity:.62,marginTop:5},primary:{padding:"10px 13px",borderRadius:10,border:0,background:"#2563eb",color:"white",fontWeight:900,whiteSpace:"nowrap"},empty:{padding:28,textAlign:"center",opacity:.6},callout:{display:"grid",gap:5,marginTop:14,padding:14,borderRadius:14,border:"1px solid #ef4444",background:"rgba(127,29,29,.12)"}};