import{useEffect,useMemo,useState}from"react";
import{useNavigate}from"react-router-dom";
import api from"../services/api";
import{useUser}from"../contexts/UserContext.jsx";

const SHIFT_TYPES=["Day","Evening","Night"],ROLE_OPTIONS=["All Staff","Nurses (RN/LPN)","RN","LPN","CNA"];
const pad=n=>String(n).padStart(2,"0"),ymd=d=>`${d.getFullYear()}-${pad(d.getMonth()+1)}-${pad(d.getDate())}`;
const monday=d=>{const x=new Date(d),day=x.getDay();x.setHours(0,0,0,0);x.setDate(x.getDate()-(day===0?6:day-1));return x};
const add=(d,n)=>{const x=new Date(d);x.setDate(x.getDate()+n);return x};
const fmtTime=t=>{if(!t)return"";const[h,m]=String(t).slice(0,5).split(":").map(Number);return new Date(2000,0,1,h,m).toLocaleTimeString("en-US",{hour:"numeric",minute:m?"2-digit":undefined}).replace(" ","").toLowerCase()};
const hours=s=>s?.start_time&&s?.end_time?Math.max(0,(new Date(s.end_time)-new Date(s.start_time))/36e5):0;
const isNurse=r=>["RN","LPN","NURSE"].includes(String(r||"").toUpperCase());
const groupRole=r=>isNurse(r)?"Nurse":String(r||"").toUpperCase()==="CNA"?"CNA":String(r||"");

export default function ScheduleMatrixPage(){
 const nav=useNavigate(),{permissions,isSuperadmin,role}=useUser(),canWrite=!!isSuperadmin||String(role||"").toLowerCase()==="superadmin"||!!permissions?.can_schedule_write,canAdmin=!!isSuperadmin||!!permissions?.is_admin;
 const[week,setWeek]=useState(()=>monday(new Date())),[shifts,setShifts]=useState([]),[staff,setStaff]=useState([]),[pto,setPto]=useState([]),[requirements,setRequirements]=useState([]),[loading,setLoading]=useState(true),[roleFilter,setRoleFilter]=useState("Nurses (RN/LPN)"),[shiftFilter,setShiftFilter]=useState("All Shifts"),[search,setSearch]=useState(""),[modal,setModal]=useState(null),[saving,setSaving]=useState(false);
 const days=useMemo(()=>Array.from({length:7},(_,i)=>add(week,i)),[week]),from=ymd(days[0]),to=ymd(days[6]);
 async function load(){setLoading(true);try{const[a,b,c,d]=await Promise.all([api.get(`/shifts?from=${from}&to=${to}`),api.get("/staff/lookup"),api.get(`/shift-requests/approved-time-off?from=${from}&to=${to}`),api.get("/coverage-requirements")]);setShifts(Array.isArray(a)?a:[]);setStaff(Array.isArray(b)?b:[]);setPto(Array.isArray(c)?c:[]);setRequirements(Array.isArray(d)?d:[])}finally{setLoading(false)}}
 useEffect(()=>{load()},[from,to]);
 const sb=useMemo(()=>Object.fromEntries(staff.map(s=>[String(s.id),s])),[staff]);
 const weekHours=useMemo(()=>{const o={};for(const s of shifts)if(s.staff_id!=null)o[s.staff_id]=(o[s.staff_id]||0)+hours(s);return o},[shifts]);
 const visibleStaff=useMemo(()=>staff.filter(s=>{const r=String(s.role||"").toUpperCase(),okRole=roleFilter==="All Staff"||roleFilter==="Nurses (RN/LPN)"&&isNurse(r)||r===roleFilter;return okRole&&(!search||String(s.name||"").toLowerCase().includes(search.toLowerCase()))}).sort((a,b)=>String(a.name).localeCompare(String(b.name))),[staff,roleFilter,search]);
 const shiftMap=useMemo(()=>{const o={};for(const s of shifts)if(s.staff_id!=null)(o[`${s.staff_id}|${s.shift_date}`]||(o[`${s.staff_id}|${s.shift_date}`]=[])).push(s);return o},[shifts]);
 const ptoMap=useMemo(()=>{const o={};for(const r of pto)for(let d=new Date(`${r.start_date}T00:00:00`),e=new Date(`${r.end_date}T00:00:00`);d<=e;d.setDate(d.getDate()+1))o[`${r.staff_id}|${ymd(d)}`]=r;return o},[pto]);
 const reqMap=useMemo(()=>Object.fromEntries(requirements.map(r=>[`${r.role_group}|${r.shift_type}`,Number(r.required_count)||0])),[requirements]);
 const configured=requirements.some(r=>Number(r.required_count)>0);
 const coverage=useMemo(()=>{let full=0,short=0;const perDay={};for(const d of days){const date=ymd(d);let dayShort=0;for(const roleGroup of["Nurse","CNA"])for(const st of SHIFT_TYPES){const req=reqMap[`${roleGroup}|${st}`]||0;if(!req)continue;const count=shifts.filter(s=>s.shift_date===date&&s.staff_id!=null&&groupRole(sb[String(s.staff_id)]?.role||s.role)===roleGroup&&s.shift_type===st).length;if(count>=req)full++;else{short+=req-count;dayShort+=req-count}}perDay[date]=dayShort}return{full,short,perDay}},[days,shifts,reqMap,sb]);
 const openCount=shifts.filter(s=>s.staff_id==null).length,ptoCount=pto.length,otCount=Object.values(weekHours).filter(h=>h>40).length;
 function shiftLabel(s){const type=s.shift_type||"Shift";const times=s.start_local&&s.end_local?`${fmtTime(s.start_local)}–${fmtTime(s.end_local)}`:"";return{type,times}}
 async function saveShift(){const f=modal?.form;if(!f?.staff_id||!f.date||!f.shift_type)return;setSaving(true);try{await api.post("/shifts",{staff_id:Number(f.staff_id),shift_date:f.date,shiftType:f.shift_type});setModal(null);await load()}catch(e){alert(e?.message||"Unable to add shift")}finally{setSaving(false)}}
 async function saveOpen(){const f=modal?.form;if(!f?.date||!f.role||!f.shift_type)return;setSaving(true);try{await api.post("/shifts/open",{role:f.role,shift_date:f.date,shiftType:f.shift_type});setModal(null);await load()}catch(e){alert(e?.message||"Unable to add open shift")}finally{setSaving(false)}}
 async function saveRules(){setSaving(true);try{await api.put("/coverage-requirements",{requirements:modal.rows});setRequirements(modal.rows);setModal(null)}catch(e){alert(e?.message||"Unable to save coverage rules")}finally{setSaving(false)}}
 if(loading)return<div style={{padding:32}}>Loading schedule…</div>;
 return <div style={page}>
  <div style={top}><div><h1 style={{margin:0,fontSize:38}}>Schedule</h1><div style={muted}>Build, manage, and review staffing by employee.</div></div><div style={toolbar}><button style={btn} onClick={()=>setWeek(monday(new Date()))}>Today</button><button style={btn} onClick={()=>setWeek(add(week,-7))}>‹</button><button style={btn} onClick={()=>setWeek(add(week,7))}>›</button><b>{days[0].toLocaleDateString("en-US",{month:"long",day:"numeric"})} – {days[6].toLocaleDateString("en-US",{month:"short",day:"numeric",year:"numeric"})}</b><button style={active}>Week</button><button style={btn} onClick={()=>nav("/shifts/month")}>Month</button></div></div>
  <div style={filters}><select style={input} value={roleFilter} onChange={e=>setRoleFilter(e.target.value)}>{ROLE_OPTIONS.map(x=><option key={x}>{x}</option>)}</select><select style={input} value={shiftFilter} onChange={e=>setShiftFilter(e.target.value)}><option>All Shifts</option>{SHIFT_TYPES.map(x=><option key={x}>{x}</option>)}</select><input style={{...input,flex:1}} placeholder="Search employees…" value={search} onChange={e=>setSearch(e.target.value)}/>{canWrite&&<button style={primary} onClick={()=>setModal({type:"open",form:{role:"Nurse",date:from,shift_type:"Day"}})}>+ Open Shift</button>}{canAdmin&&<button style={btn} onClick={()=>setModal({type:"rules",rows:requirements.map(x=>({...x}))})}>Coverage Rules</button>}<button style={btn} onClick={()=>window.print()}>Print</button></div>
  <div style={cards}><Summary title="Coverage" value={configured?(coverage.short?`${coverage.short} short`:`${coverage.full} covered`):"Not configured"} tone={configured?(coverage.short?"warn":"ok"):"neutral"}/><Summary title="Open Shifts" value={openCount} tone={openCount?"info":"neutral"}/><Summary title="PTO / Leave" value={ptoCount} tone="purple"/><Summary title="Overtime Risk" value={otCount} tone={otCount?"warn":"neutral"}/></div>
  {!configured&&<div style={notice}>Coverage rules are not configured yet. Set required Nurses and CNAs per shift to turn on automatic coverage status.</div>}
  <div style={tableWrap}><table style={table}><thead><tr><th style={stickyHead}>Employee</th>{days.map(d=><th key={ymd(d)} style={th}><div>{d.toLocaleDateString("en-US",{weekday:"short"})}</div><small>{d.toLocaleDateString("en-US",{month:"short",day:"numeric"})}</small>{configured&&<div style={{fontSize:11,marginTop:5,color:coverage.perDay[ymd(d)]?"#f59e0b":"#22c55e"}}>{coverage.perDay[ymd(d)]?`⚠ ${coverage.perDay[ymd(d)]} short`:"✓ Covered"}</div>}</th>)}<th style={th}>Total</th></tr></thead><tbody>
   {visibleStaff.map(p=><tr key={p.id}><td style={stickyCell}><b>{p.name}</b><div style={mutedSmall}>{p.role} · <span style={{color:(weekHours[p.id]||0)>40?"#ef4444":"inherit"}}>{Math.round((weekHours[p.id]||0)*10)/10}h</span>{(weekHours[p.id]||0)>40&&" ⚠"}</div></td>{days.map(d=>{const date=ymd(d),leave=ptoMap[`${p.id}|${date}`],rows=(shiftMap[`${p.id}|${date}`]||[]).filter(s=>shiftFilter==="All Shifts"||s.shift_type===shiftFilter);return <td key={date} style={td} onDoubleClick={()=>canWrite&&setModal({type:"shift",form:{staff_id:String(p.id),date,shift_type:"Day"}})}>{leave&&<div style={ptoBox}>✈ PTO</div>}{rows.map(s=>{const l=shiftLabel(s);return <div key={s.id} style={s.shift_type==="Night"?nightBox:shiftBox}><b>{l.type}</b><small>{l.times}</small></div>)}{!leave&&!rows.length&&<span style={{opacity:.25}}>—</span>}</td>})}<td style={{...td,fontWeight:900}}>{Math.round((weekHours[p.id]||0)*10)/10}h</td></tr>)}
   {canWrite&&<tr><td style={stickyCell}><b>Open Coverage</b></td>{days.map(d=>{const date=ymd(d),rows=shifts.filter(s=>s.staff_id==null&&s.shift_date===date&&(shiftFilter==="All Shifts"||s.shift_type===shiftFilter));return <td key={date} style={td}>{rows.map(s=><div key={s.id} style={openBox}>+ OPEN<small>{groupRole(s.role)} · {s.shift_type}</small></div>)}</td>})}<td style={td}>—</td></tr>}
  </tbody></table></div>
  {modal&&<Modal onClose={()=>!saving&&setModal(null)}>{modal.type==="shift"?<><h2>Add Shift</h2><label style={lab}>Employee<select style={input} value={modal.form.staff_id} onChange={e=>setModal(m=>({...m,form:{...m.form,staff_id:e.target.value}}))}>{staff.map(s=><option value={s.id} key={s.id}>{s.name} ({s.role})</option>)}</select></label><label style={lab}>Date<input style={input} type="date" value={modal.form.date} onChange={e=>setModal(m=>({...m,form:{...m.form,date:e.target.value}}))}/></label><label style={lab}>Shift<select style={input} value={modal.form.shift_type} onChange={e=>setModal(m=>({...m,form:{...m.form,shift_type:e.target.value}}))}>{SHIFT_TYPES.map(x=><option key={x}>{x}</option>)}</select></label><button style={primary} disabled={saving} onClick={saveShift}>{saving?"Saving…":"Add Shift"}</button></>:modal.type==="open"?<><h2>Post Open Shift</h2><label style={lab}>Coverage<select style={input} value={modal.form.role} onChange={e=>setModal(m=>({...m,form:{...m.form,role:e.target.value}}))}><option value="Nurse">Nurse (RN/LPN)</option><option value="CNA">CNA</option></select></label><label style={lab}>Date<input style={input} type="date" value={modal.form.date} onChange={e=>setModal(m=>({...m,form:{...m.form,date:e.target.value}}))}/></label><label style={lab}>Shift<select style={input} value={modal.form.shift_type} onChange={e=>setModal(m=>({...m,form:{...m.form,shift_type:e.target.value}}))}>{SHIFT_TYPES.map(x=><option key={x}>{x}</option>)}</select></label><button style={primary} disabled={saving} onClick={saveOpen}>{saving?"Posting…":"Post Open Shift"}</button></>:<><h2>Coverage Rules</h2><p style={muted}>Required staff for each shift. These rules apply to every day of the week.</p>{["Nurse","CNA"].map(r=><div key={r} style={{marginBottom:18}}><b>{r}</b><div style={{display:"grid",gridTemplateColumns:"repeat(3,1fr)",gap:10,marginTop:8}}>{SHIFT_TYPES.map(st=>{const i=modal.rows.findIndex(x=>x.role_group===r&&x.shift_type===st),row=i>=0?modal.rows[i]:{role_group:r,shift_type:st,required_count:0};return <label style={lab} key={st}>{st}<input style={input} type="number" min="0" max="100" value={row.required_count} onChange={e=>{const n=Number(e.target.value)||0;setModal(m=>{const rows=[...m.rows],idx=rows.findIndex(x=>x.role_group===r&&x.shift_type===st);if(idx>=0)rows[idx]={...rows[idx],required_count:n};else rows.push({role_group:r,shift_type:st,required_count:n});return{...m,rows}})}}/></label>})}</div></div>)}<button style={primary} disabled={saving} onClick={saveRules}>{saving?"Saving…":"Save Coverage Rules"}</button></>}</Modal>}
 </div>
}
function Summary({title,value,tone}){const tones={ok:["#062d1d","#22c55e"],warn:["#332107","#f59e0b"],info:["#08233d","#38bdf8"],purple:["#251438","#c084fc"],neutral:["#171717","#6b7280"]},[bg,border]=tones[tone]||tones.neutral;return <div style={{padding:18,borderRadius:14,border:`1px solid ${border}55`,background:bg}}><div style={muted}>{title}</div><div style={{fontSize:26,fontWeight:900,marginTop:4}}>{value}</div></div>}
function Modal({children,onClose}){return <div style={overlay} onMouseDown={onClose}><div style={dialog} onMouseDown={e=>e.stopPropagation()}>{children}</div></div>}
const page={padding:"24px 28px 40px",maxWidth:1700,margin:"0 auto"},top={display:"flex",justifyContent:"space-between",alignItems:"center",gap:20,flexWrap:"wrap"},toolbar={display:"flex",alignItems:"center",gap:8,flexWrap:"wrap"},filters={display:"flex",gap:10,margin:"22px 0 14px",flexWrap:"wrap"},cards={display:"grid",gridTemplateColumns:"repeat(4,minmax(170px,1fr))",gap:12,marginBottom:14},notice={padding:"12px 14px",border:"1px solid #a16207",background:"#2b2008",borderRadius:10,marginBottom:14,color:"#fde68a"},tableWrap={overflow:"auto",border:"1px solid var(--border)",borderRadius:14},table={width:"100%",borderCollapse:"separate",borderSpacing:0,minWidth:1180},th={padding:"13px 10px",borderBottom:"1px solid var(--border)",borderRight:"1px solid var(--border)",textAlign:"center",background:"var(--nav-bg)",minWidth:120},stickyHead={...{padding:"13px 14px",borderBottom:"1px solid var(--border)",borderRight:"1px solid var(--border)",textAlign:"left",background:"var(--nav-bg)",minWidth:210},position:"sticky",left:0,zIndex:3},stickyCell={padding:"12px 14px",borderBottom:"1px solid var(--border)",borderRight:"1px solid var(--border)",background:"var(--bg)",position:"sticky",left:0,zIndex:2,minWidth:210},td={padding:7,borderBottom:"1px solid var(--border)",borderRight:"1px solid var(--border)",textAlign:"center",height:68,verticalAlign:"middle"},shiftBox={display:"grid",gap:2,textAlign:"left",padding:"8px 9px",borderRadius:9,border:"1px solid #22c55e",background:"#08351f",margin:"2px 0"},nightBox={display:"grid",gap:2,textAlign:"left",padding:"8px 9px",borderRadius:9,border:"1px solid #3b82f6",background:"#0b2850",margin:"2px 0"},ptoBox={padding:"10px",borderRadius:9,border:"1px solid #a855f7",background:"#34134b",fontWeight:900},openBox={display:"grid",gap:2,textAlign:"left",padding:"8px 9px",borderRadius:9,border:"1px solid #38bdf8",background:"#0a2940",fontWeight:900,margin:"2px 0"},btn={background:"transparent",color:"inherit",border:"1px solid var(--border)",borderRadius:10,padding:"10px 14px",fontWeight:800},active={background:"#0b4ea2",color:"white",border:"1px solid #3b82f6",borderRadius:10,padding:"10px 18px",fontWeight:900},primary={background:"#2563eb",color:"white",border:"1px solid #3b82f6",borderRadius:10,padding:"10px 16px",fontWeight:900},input={background:"var(--card-bg)",color:"inherit",border:"1px solid var(--border)",borderRadius:10,padding:"10px 12px",minWidth:150},muted={opacity:.65},mutedSmall={opacity:.65,fontSize:13,marginTop:4},lab={display:"grid",gap:6,fontWeight:800,margin:"12px 0"},overlay={position:"fixed",inset:0,background:"rgba(0,0,0,.7)",display:"grid",placeItems:"center",zIndex:9999,padding:20},dialog={width:"min(620px,94vw)",maxHeight:"88vh",overflow:"auto",background:"var(--bg)",border:"1px solid var(--border)",borderRadius:16,padding:24,boxShadow:"0 24px 80px rgba(0,0,0,.45)"};
