import { useEffect, useMemo, useRef, useState } from "react";
import api from "../services/api";
import { useUser } from "../contexts/UserContext.jsx";

function ymd(d){const x=new Date(d);return `${x.getFullYear()}-${String(x.getMonth()+1).padStart(2,"0")}-${String(x.getDate()).padStart(2,"0")}`;}
function calendarRange(month){const first=new Date(month.getFullYear(),month.getMonth(),1),last=new Date(month.getFullYear(),month.getMonth()+1,0);const from=new Date(first);from.setDate(first.getDate()-first.getDay());const to=new Date(last);to.setDate(last.getDate()+(6-last.getDay()));return{from:ymd(from),to:ymd(to)};}
function weekStart(dateStr){const d=new Date(`${dateStr}T00:00:00`);d.setDate(d.getDate()-d.getDay());return ymd(d);}
function shiftHours(s){if(s?.start_time&&s?.end_time){const n=(new Date(s.end_time)-new Date(s.start_time))/3600000;return Number.isFinite(n)&&n>0?n:0;}if(s?.start_local&&s?.end_local){const [sh,sm]=String(s.start_local).split(":").map(Number),[eh,em]=String(s.end_local).split(":").map(Number);let n=(eh+em/60)-(sh+sm/60);if(n<0)n+=24;return Number.isFinite(n)?n:0;}return 0;}
function esc(v){return String(v??"").replaceAll("&","&amp;").replaceAll("<","&lt;").replaceAll(">","&gt;").replaceAll('"',"&quot;").replaceAll("'","&#039;");}

export default function SchedulePage(){
 const {permissions,isSuperadmin,role,orgName}=useUser();
 const canWrite=!!isSuperadmin||String(role||"").toLowerCase()==="superadmin"||!!permissions?.can_schedule_write;
 const[shifts,setShifts]=useState([]),[staff,setStaff]=useState([]),[month,setMonth]=useState(()=>new Date(new Date().getFullYear(),new Date().getMonth(),1)),[modal,setModal]=useState(null),[form,setForm]=useState({staffId:"",date:"",shiftType:""}),[loading,setLoading]=useState(true),[saving,setSaving]=useState(false),[search,setSearch]=useState(""),[roleFilter,setRoleFilter]=useState("All"),[shiftFilter,setShiftFilter]=useState("All");const monthRequest=useRef(0);
 async function loadMonth(m=month){const requestId=++monthRequest.current;const{from,to}=calendarRange(m);const s=await api.get(`/shifts?from=${from}&to=${to}`);if(requestId===monthRequest.current)setShifts(Array.isArray(s)?s:[]);}
 useEffect(()=>{let alive=true;(async()=>{setLoading(true);try{const[p]=await Promise.all([api.get("/staff/lookup"),loadMonth(month)]);if(alive)setStaff(Array.isArray(p)?p:[]);}finally{if(alive)setLoading(false)}})();return()=>{alive=false;monthRequest.current++;};},[]);
 useEffect(()=>{if(!loading)loadMonth(month);},[month]);
 const staffById=useMemo(()=>Object.fromEntries(staff.map(s=>[String(s.id),s])),[staff]);
 const roles=useMemo(()=>["All",...Array.from(new Set(staff.map(s=>String(s.role||"").trim()).filter(Boolean))).sort()],[staff]);
 const visibleShifts=useMemo(()=>shifts.filter(s=>{const p=staffById[String(s.staff_id)]||{};if(search&&!String(p.name||"").toLowerCase().includes(search.toLowerCase()))return false;if(roleFilter!=="All"&&String(p.role||s.role)!==roleFilter)return false;if(shiftFilter!=="All"&&String(s.shift_type)!==shiftFilter)return false;return true;}),[shifts,staffById,search,roleFilter,shiftFilter]);
 const days=useMemo(()=>{const first=new Date(month.getFullYear(),month.getMonth(),1),last=new Date(month.getFullYear(),month.getMonth()+1,0),out=Array(first.getDay()).fill(null);for(let i=1;i<=last.getDate();i++)out.push(new Date(month.getFullYear(),month.getMonth(),i));return out},[month]);
 const byDate=useMemo(()=>{const map={};visibleShifts.forEach(s=>{if(s?.shift_date&&(new Date(`${s.shift_date}T00:00:00`)).getMonth()===month.getMonth()&&(new Date(`${s.shift_date}T00:00:00`)).getFullYear()===month.getFullYear())(map[s.shift_date]||(map[s.shift_date]=[])).push(s)});Object.values(map).forEach(a=>a.sort((x,y)=>String(x.start_local||"").localeCompare(String(y.start_local||""))));return map},[visibleShifts,month]);
 const weeklyHours=useMemo(()=>{const out={};shifts.forEach(s=>{if(!s.shift_date||!s.staff_id)return;const key=`${s.staff_id}|${weekStart(s.shift_date)}`;out[key]=(out[key]||0)+shiftHours(s)});return out},[shifts]);
 function openNew(date){if(!canWrite)return;setForm({staffId:"",date:ymd(date),shiftType:""});setModal({mode:"new"})}function openEdit(shift){if(!canWrite)return;setForm({staffId:String(shift.staff_id||""),date:shift.shift_date||"",shiftType:shift.shift_type||""});setModal({mode:"edit",shift})}
 async function save(){if(!canWrite)return;if(!form.staffId||!form.date||!form.shiftType)return alert("Select staff, date, and shift type.");const payload={staff_id:Number(form.staffId),shift_date:form.date,shiftType:form.shiftType};setSaving(true);try{const saved=modal?.mode==="edit"?await api.put(`/shifts/${modal.shift.id}`,payload):await api.post("/shifts",payload);if(saved){setShifts(cur=>{const rest=modal?.mode==="edit"?cur.filter(x=>String(x.id)!==String(modal.shift.id)):cur;const{from,to}=calendarRange(month);return saved.shift_date>=from&&saved.shift_date<=to?[...rest,saved]:rest})}setModal(null)}catch(e){alert(e?.message||"Unable to save shift.")}finally{setSaving(false)}}
 async function remove(){if(!canWrite||!modal?.shift?.id||!window.confirm("Delete this shift?"))return;setSaving(true);try{await api.delete(`/shifts/${modal.shift.id}`);setShifts(cur=>cur.filter(x=>String(x.id)!==String(modal.shift.id)));setModal(null)}finally{setSaving(false)}}
 function printMonth(){const title=month.toLocaleDateString("en-US",{month:"long",year:"numeric"});const rows=[];Object.keys(byDate).sort().forEach(date=>(byDate[date]||[]).forEach(s=>{const p=staffById[String(s.staff_id)]||{};rows.push(`<tr><td>${esc(date)}</td><td>${esc(p.name||`Staff #${s.staff_id}`)}</td><td>${esc(p.role||s.role||"")}</td><td>${esc(s.shift_type||"")}</td><td>${esc(s.start_local||"")}–${esc(s.end_local||"")}</td></tr>`)}));const w=window.open("","_blank","noopener,noreferrer");if(!w)return alert("Allow pop-ups to print the schedule.");w.document.write(`<!doctype html><html><head><title>${esc(title)} Schedule</title><style>body{font-family:Arial,sans-serif;padding:28px;color:#111}h1{margin-bottom:4px}p{margin-top:0;color:#555}table{width:100%;border-collapse:collapse;margin-top:20px}th,td{border:1px solid #bbb;padding:8px;text-align:left;font-size:12px}th{background:#eee}@media print{button{display:none}}</style></head><body><h1>${esc(orgName||"ShiftCensus")}</h1><p>${esc(title)} Schedule${search||roleFilter!=="All"||shiftFilter!=="All"?" — filtered view":""}</p><table><thead><tr><th>Date</th><th>Staff</th><th>Role</th><th>Shift</th><th>Time</th></tr></thead><tbody>${rows.join("")||"<tr><td colspan='5'>No scheduled shifts.</td></tr>"}</tbody></table><script>window.onload=()=>window.print()</script></body></html>`);w.document.close();}
 if(loading)return <div style={{padding:32}}>Loading schedule…</div>;
 return <div style={{padding:24,color:"var(--text)"}}><div style={{display:"flex",justifyContent:"space-between",alignItems:"center",gap:12,flexWrap:"wrap",marginBottom:18}}><div><h1 style={{margin:0}}>Schedule</h1><div style={{opacity:.65,marginTop:4}}>Schedule who is working. Unit placement happens separately in Assignments.</div>{!canWrite&&<div style={{marginTop:6,fontWeight:800,color:"#f59e0b"}}>Read-only schedule access</div>}</div><div style={{display:"flex",gap:8,alignItems:"center",flexWrap:"wrap"}}><button onClick={printMonth} style={btn}>Print</button><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()-1,1))} style={btn}>◀</button><strong>{month.toLocaleDateString("en-US",{month:"long",year:"numeric"})}</strong><button onClick={()=>setMonth(new Date(month.getFullYear(),month.getMonth()+1,1))} style={btn}>▶</button></div></div>
 <div style={{display:"grid",gridTemplateColumns:"minmax(180px,2fr) minmax(130px,1fr) minmax(130px,1fr) auto",gap:8,marginBottom:16}}><input value={search} onChange={e=>setSearch(e.target.value)} placeholder="Search staff…" style={input}/><select value={roleFilter} onChange={e=>setRoleFilter(e.target.value)} style={input}>{roles.map(r=><option key={r}>{r}</option>)}</select><select value={shiftFilter} onChange={e=>setShiftFilter(e.target.value)} style={input}><option>All</option><option>Day</option><option>Evening</option><option>Night</option></select><button onClick={()=>{setSearch("");setRoleFilter("All");setShiftFilter("All")}} style={btn}>Clear</button></div>
 <div style={{fontSize:12,opacity:.7,marginBottom:10}}>Weekly hour badges use scheduled shift span. Red indicates more than 40 scheduled hours in that Sunday–Saturday week; meal deductions are not applied.</div>
 <div style={{display:"grid",gridTemplateColumns:"repeat(7,minmax(0,1fr))",gap:6,marginBottom:6,opacity:.65,fontSize:12,textAlign:"center"}}>{["Sun","Mon","Tue","Wed","Thu","Fri","Sat"].map(x=><div key={x}>{x}</div>)}</div><div style={{display:"grid",gridTemplateColumns:"repeat(7,minmax(0,1fr))",gap:6}}>{days.map((date,i)=>{if(!date)return <div key={`b-${i}`} style={blank}/>;const key=ymd(date),rows=byDate[key]||[];return <div key={key} onClick={()=>openNew(date)} style={{...cell,cursor:canWrite?"pointer":"default"}}><div style={{display:"flex",justifyContent:"space-between",marginBottom:6}}><b>{date.getDate()}</b><span style={{fontSize:10,opacity:.6}}>{rows.length||""}</span></div><div style={{display:"grid",gap:4}}>{rows.map(s=>{const person=staffById[String(s.staff_id)]||{};const wh=weeklyHours[`${s.staff_id}|${weekStart(s.shift_date)}`]||0;return <button key={s.id} disabled={!canWrite} onClick={e=>{e.stopPropagation();openEdit(s)}} style={{...shiftBtn,cursor:canWrite?"pointer":"default"}}><span style={{fontWeight:800}}>{person.name||`Staff #${s.staff_id}`}</span><span style={{opacity:.65,fontSize:10}}>{person.role||s.role} · {s.shift_type||"Shift"}</span>{wh>=32&&<span style={{fontSize:10,fontWeight:900,color:wh>40?"#ef4444":"#f59e0b"}}>{wh>40?"OT risk":"Weekly"} {wh.toFixed(wh%1?1:0)}h</span>}</button>})}</div></div>})}</div>
 {modal&&<div style={overlay} onMouseDown={()=>!saving&&setModal(null)}><div style={modalStyle} onMouseDown={e=>e.stopPropagation()}><h2 style={{marginTop:0}}>{modal.mode==="edit"?"Edit scheduled shift":"Schedule staff"}</h2><label style={label}>Staff<select value={form.staffId} onChange={e=>setForm(f=>({...f,staffId:e.target.value}))} style={input}><option value="">Select staff…</option>{staff.map(s=><option key={s.id} value={s.id}>{s.name} ({s.role})</option>)}</select></label><label style={label}>Date<input type="date" value={form.date} onChange={e=>setForm(f=>({...f,date:e.target.value}))} style={input}/></label><label style={label}>Shift<select value={form.shiftType} onChange={e=>setForm(f=>({...f,shiftType:e.target.value}))} style={input}><option value="">Select shift…</option><option>Day</option><option>Evening</option><option>Night</option></select></label><div style={{display:"flex",justifyContent:"space-between",gap:8,marginTop:16}}><div>{modal.mode==="edit"&&<button disabled={saving} onClick={remove} style={{...btn,borderColor:"#7f1d1d",color:"#fca5a5"}}>Delete</button>}</div><div style={{display:"flex",gap:8}}><button disabled={saving} onClick={()=>setModal(null)} style={btn}>Cancel</button><button disabled={saving} onClick={save} style={{...btn,background:"#2563eb",color:"white"}}>{saving?"Saving…":"Save"}</button></div></div></div></div>}</div>;
}
const btn={padding:"9px 12px",borderRadius:10,border:"1px solid var(--border)",background:"var(--surface)",color:"inherit",fontWeight:800};const blank={minHeight:96,borderRadius:10,background:"var(--surface-glass)"};const cell={minHeight:112,border:"1px solid var(--border)",borderRadius:10,padding:8,background:"var(--surface)"};const shiftBtn={display:"grid",textAlign:"left",gap:2,padding:"6px 7px",borderRadius:7,border:"1px solid var(--border)",background:"var(--surface-glass)",color:"inherit"};const overlay={position:"fixed",inset:0,background:"rgba(0,0,0,.65)",display:"grid",placeItems:"center",zIndex:10000,padding:18};const modalStyle={width:"min(460px,95vw)",background:"#111",border:"1px solid #333",borderRadius:16,padding:20,color:"white"};const label={display:"grid",gap:6,marginBottom:12,fontWeight:800};const input={padding:"11px 12px",borderRadius:10,border:"1px solid var(--border)",background:"var(--surface)",color:"inherit",minWidth:0};